<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.enterprisex</groupId>
        <artifactId>enterprisex-framework</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>enterprisex-common</artifactId>
    <packaging>pom</packaging>

    <description>公共模块父工程</description>

    <modules>
        <module>common-core</module>
        <module>common-security</module>
        <module>common-redis</module>
        <module>common-datasource</module>
        <module>common-log</module>
        <module>common-swagger</module>
        <module>common-mybatis</module>
        <module>common-excel</module>
    </modules>

</project>
